stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  script:
    # install dpl:
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY