stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  image: "ruby"
  script:
    # install dpl:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app_name=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY